### ISSUE TITLE
Count in list in range return 0 elements

### ISSUE THREAD

**Issue by UAN-East-Frontier** [Gensokyo-Mangekyo/RailwayCSharp#3]
Enter range 00:25, 05:30 and it return 0

**Comment by UAN-East-Frontier** [comment]
False in condition CheckTimeEnd!!!
![image](https://github.com/Gensokyo-Mangekyo/RailwayCSharp/assets/108526422/2d3419a8-9561-451c-9b5f-9243ffac31e1)

**Comment by Gensokyo-Mangekyo** [comment]
Method CheckTimeStart and CheckTimeEnd were misspelled.
![image](https://github.com/Gensokyo-Mangekyo/RailwayCSharp/assets/108526422/5b4bfd5c-2641-4c63-afeb-e813326ab394)
